### ISSUE TITLE
any ways to reduce compile time?

### ISSUE THREAD

**Issue by eetoa** [llxiaoyuan/oxorany#6]
encrypys 100 plus strings in my project, took more than 10min compile time.
any suggestions? thnx.

**Comment by Xniveres** [comment]
hey, try using clang and it should work quickly,

msvc has a lot of issues with __forceinline

**Comment by llxiaoyuan** [comment]
#define OXORANY_DISABLE_OBFUSCATION
OR
Simplify the decrypt function

**Comment by eetoa** [comment]
> 

it works, thnx. 
great project.
